SpawnRate 9
WifeSpawn 1
LockNLoad 1
GunSpawnRate 23
WepSpawnRate 11
HostileSpawnRate 21
MaxHostileSpawnRate 21
InfinitAmmo 2
NoPreSetSpawn 2
SafeBase 1
SurvivorBases 1
FindWork 2
SurvivorHunger 2
SurvivorFriendliness 6
RaidersAtLeastHours 20
RaidersAfterHours 22
RaidersChance 3
Bravery 3
SSHotkey1 6
SSHotkey2 10
SSHotkey3 27
SSHotkey4 42
DebugOptions 1
NoIdleChatter 2
Option_WarningMSG 2
Option_Perception_Bonus 2
Option_FollowDistance 5
Option_ForcePVP 2
Option_Panic_Distance 21
Option_Display_Survivor_Names 1
Option_Display_Hostile_Color 1
AltSpawn 5
AltSpawnPercent 91
AltSpawnAmount 5
ForcePVP 2
RoleplayMessage 1
FollowDistance 1
Perception_Bonus 2
Panic_Distance 11
DebugSay 1
DebugSay_Distance 1
WarningMSG 1
